### ISSUE TITLE
Adehabitat relocations for building polygons

### ISSUE THREAD

**Issue by echinorhinus** [ropensci/spatsoc#29]
Another question (sorry!)

Working through the vignette, I hit an ADEHabitat related error when building polygons.
I get the same message whether using “build_polys”, “group_polys” or “area_DT”.
The message is as follows:

Error in (function (xy, h = "href", grid = 60, same4all = FALSE, hlim = c(0.1,  : 
  At least 5 relocations are required to fit an home range

I have tried massively increasing the grid size to allow for “relocations” but still get the same error message. 

Is there a way to reduce the number of relocations required?

Any suggestions?

**Comment by robitalec** [comment]
No worries! 

I'm assuming you mean working through the vignette, but with your own data right? (If not - let me know).

So this error from `adehabitatHR` has less to do with the grid size and more to do with the number of relocations. In this case, the number of relocations in each timegroup. 

We need to check that you have at least 5 relocations for an individual in the timegroup. 

```r
# Load data.table
library(data.table)

# Read example data
DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))

# Cast the character column to POSIXct
DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]

# Proj4 string for example data
utm <- '+proj=utm +zone=36 +south +ellps=WGS84 +datum=WGS84 +units=m +no_defs'


# Check that there are sufficient observations for each individual
DT[, .N, by = ID]

```

```
        ID     N
    <char> <int>
 1:      A  1396
 2:      B  1440
 3:      C  1433
 4:      D  1424
 5:      E  1434
 6:      F  1440
 7:      G  1430
 8:      H  1435
 9:      I  1435
10:      J  1430
```

```r
# Alternatively, if we are going to use the splitBy argument to build, for example, yearly home ranges
DT[, yr := year(datetime)]

# Check that there are sufficient observations for each individual
DT[, .N, by = .(ID, yr]
```

```
        ID    yr     N
    <char> <int> <int>
 1:      A  2016   732
 2:      A  2017   664
 3:      B  2016   732
 4:      B  2017   708
 5:      C  2016   727
 6:      C  2017   706
 7:      D  2016   730
 8:      D  2017   694
 9:      E  2016   729
10:      E  2017   705
11:      F  2016   732
12:      F  2017   708
13:      G  2016   726
14:      G  2017   704
15:      H  2016   728
16:      H  2017   707
17:      I  2016   730
18:      I  2017   705
19:      J  2016   726
20:      J  2017   704
        ID    yr     N
```

So with your data, make sure that this returns TRUE for all individuals.

```r
DT[, .N > 5, by = .(ID, yr)]
```
