### ISSUE TITLE
please release spatsoc to CRAN if possible

### ISSUE THREAD

**Issue by mattdowle** [ropensci/spatsoc#33]
Hi Alex,

Thanks for making the change in #32.

Currently, datetimes without any timezone indicator (i.e. unmarked datetime) are read by `fread` as type `character`.  We'd like to change this to read unmarked datetime as `UTC POSIXct` rather than `character`. But if we make this change, spatsoc-dev needs to be released to CRAN, otherwise spatsoc 0.1.14 will start to fail CRAN checks. When the `TZ` environment variable is set to `UTC`, unmarked datetime are already read as `POSIXct`. I set `TZ=UTC` in my revdep testing, `spatsoc` came up in https://github.com/Rdatatable/data.table/issues/4758, which is how I know spatsoc is the only package affected. Which is good because it gives us confidence this change is the right way forward. It's undesirable for the output type of a function call (`character` vs `POSIXct` in this case) to depend on an environment variable (`TZ` in this case). So this is what we'd like to tidy up, to make consistent and predictable.

Would it be possible to release spatsoc-dev to CRAN within a few weeks perhaps?

Best, Matt

**Comment by robitalec** [comment]
Hey @mattdowle, going to submit to CRAN today. 
Keep you posted!

**Comment by robitalec** [comment]
v0.1.15 with this fix on CRAN now. 
Thanks!

**Comment by mattdowle** [comment]
Fantastic. Many thanks, @robitalec!!
