### ISSUE TITLE
Failures in test-group-lines

### ISSUE THREAD

**Issue by rsbivand** [ropensci/spatsoc#34]
You expect sp/rgdal to be silent when you handle CRS objects possibly without paying attention to changes in **rgdal** and **sf** since early 2020, see https://www.r-spatial.org/r/2020/03/17/wkt.html. I have not seen the failure before, and is caused by forthcoming PROJ 8.0.0 (used by **sp** via **rgdal**).

```

> source("test-group-lines.R", echo=TRUE)
...
── Failure (test-group-lines.R:196:3): threshold is correctly provided, or error ─────────────────────
`group_lines(...)` produced warnings.
...
```

**Comment by robitalec** [comment]
Thank you for your report @rsbivand. 

Please clarify what you mean by:

> changes since early 2000

**Comment by rsbivand** [comment]
Edited in place. You should in general never expect silence from anything you do not control yourself, the lack of silence is providing you with information you may choose to acknowledge. Tests of this kind are far less helpful than regular tests (not testthat), which yield diff visually - you can see what changed.

**Comment by robitalec** [comment]
Thank you for your clarification. 

Please post the sessionInfo() and GDAL/PROJ/GEOS versions used to reproduce this.

**Comment by rsbivand** [comment]
Install PROJ 8.0.0RC1 http://download.osgeo.org/proj/proj-8.0.0RC1.tar.gz, rebuild GDAL (I used 3.2.1 and 3.3.0 main HEAD), and then install rgdal from CRAN. If you then wish to check that rgdal has resolved your issue, install rgdal from R-Forge and re-run spatsoc checks. 

If this looks hard, trust me - you need to drop the test or merge my option which tells sp and rgdal not to warn, until the revised rgdal is released. Note that you should not be using "+init=" now, it may go away shortly as PROJ evolves; you may need to condition on sp versions. Do consider reading https://www.r-spatial.org/r/2020/03/17/wkt.html and https://cran.r-project.org/web/packages/rgdal/vignettes/CRS_projections_transformations.html which explain how PROJ is changing.

**Comment by robitalec** [comment]
Thank you for specifying which PROJ and GDAL versions you used. 

Please post your sessionInfo() for system and R package versions to reproduce this. 

The language in https://www.r-spatial.org/r/2020/03/17/wkt.html#crs-objects-in-sp could be clearer that "+init=" should not be used, rather than "SRS_string='EPSG:4326'" is simply preferred. 

![image](https://user-images.githubusercontent.com/16324625/108750388-86bc8280-751b-11eb-8827-cbecf985e649.png)

**Comment by rsbivand** [comment]
```
> sessionInfo()
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Fedora 33 (Workstation Edition)

Matrix products: default
BLAS:   /home/rsb/topics/R/R404-share/lib64/R/lib/libRblas.so
LAPACK: /home/rsb/topics/R/R404-share/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rgdal_1.5-24 sp_1.4-5    

loaded via a namespace (and not attached):
[1] compiler_4.0.4  grid_4.0.4      lattice_0.20-41
```
The rgdal version is not important, 1.5-23 and 1.5-24 rev 1129 behave the same.

Do not complain about lack of clarity - there really is no clarity (read the PROJ mailing list). We are doing what we can to insulate package maintainers from upstream changes, so nothing written a year ago  will communicate much now. The current concern, and the one that raised this issue, is that in the updated version of the EPSG database bundled with PROJ, what used to be known as DATUM objects are ENSEMBLE objects if multiple instances use the same DATUM name. WGS84 is particularly affected - there are multiple epochs since 1984, and in addition the tectonic plates have shifted a good deal in the intervening 30+ years. So trivialities like +init= are among the least of the problems that we are trying to insulate package maintainers from.

In your case, we can hope that CRAN does not upgrade to PROJ 8.0.0 next week (or when Debian upgrades) before I release rgdal (I am not in a hurry). If they do upgrade PROJ, CRAN checks will fail for spatsoc on all platforms with PROJ 8.0.0, because you expect_silent() in the affected test. So to be on the safe side, and not force me to release rgdal, you should consider updating spatsoc urgently. 

If you find rgdal unhelpful, please feel free to move to sf, in fact all packages begun after sf was first released should have done so. This would relieve the pressure on sp, rgeos and rgdal which are getting harder to maintain as time passes.

**Comment by rsbivand** [comment]
A clarifying note - this issue arose out of running R CMD check on 986 packages using spatial infrastructure packages like sp, sf, rgdal, rgeos, raster, etc., of which only two failures could be attributed to upgrading PROJ  from 7.2.1 to 8.0.0. This is one of those failures, analysis of which let me add an additional check in rgdal to let ENSEMBLE be seen as equivalent to DATUM in WKT2_2019 representations.

**Comment by robitalec** [comment]
Roger, please consider your tone in subsequent responses. 
You have already had comments removed in this repository for being disrespectful and breaking the [Code of Conduct](https://github.com/ropensci/spatsoc/blob/master/CODE_OF_CONDUCT.md). 
I would have expected that this would be a warning for the future, but if you need it to be explicit once more:

You need to treat others with respect and dignity in all interactions here. Anything less than that will not be tolerated. 

---

When we have made the necessary changes I will comment here and close the issue.

**Comment by rsbivand** [comment]
Investigating the PROJ 8.0.0 issue underlying this test failure has been useful anyway, and very possibly caching repeated CRS lookups (see issue in sp repo above). You do not need to do anything,  an **rgdal** release will prevent **spatsoc** failing.

**Comment by robitalec** [comment]
Ok. Closing this. Changes to tests and new emphasis on 'EPSG' instead of '+init:' added throughout man, vignettes, etc merged and submitted to CRAN.

**Comment by rsbivand** [comment]
Thanks. Please note that the EPSG idiom works  with **sp** >= 1.4-4, and PROJ >= 6 accessed through **rgdal** from `sp::CRS()`. The Solaris check platform still uses PROJ 5.2.0. If that becomes a problem, please get in touch and I'll try to introduce a work-around in `sp::CRS()` to substitute back to `+init=epsg:` when PROJ < 6.
