### ISSUE TITLE
dyadic pairing with GPS data

### ISSUE THREAD

**Issue by qwebber** [ropensci/spatsoc#7]
It would be interesting to have a function that detects the number of consecutive relocations for a pair of individuals (dyad) based on the buffer/threshold setting provided in group_times.

**Comment by robitalec** [comment]
Cool Quinn! 
What kinds of definitions would be useful for dyad pairs? 
Simply n consecutive grouping from `group_pts` for a pair of individuals?

**Comment by robitalec** [comment]
This has been initially implemented by `dyad_id`. Further plans to extend to triads, etc if there is interest. 

For now, the workflow is generate edges, and assign a dyad id. 

```r
# Load packages
library(spatsoc)
library(data.table)

# Read example data
DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))

# Cast the character column to POSIXct
DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]

# Temporal grouping
group_times(DT, datetime = 'datetime', threshold = '20 minutes')

# Edge list generation
edges <- edge_dist(
  DT,
  threshold = 100,
  id = 'ID',
  coords = c('X', 'Y'),
  timegroup = 'timegroup',
  returnDist = TRUE,
  fillNA = TRUE
)

# Generate dyad IDs
dyad_id(edges, 'ID1', 'ID2')

# Generate dyad IDs
dyad_id(edges, 'ID1', 'ID2')
```

After assigning a dyadID, we can measure things like consecutive relocations together, start and end times, mean X Y for dyads, etc. (vignette coming)

```r
# How many observations of each dyad? (N / 2 because edges have both A->B and B->A)
edges[, .N / 2, dyadID]
```
